
  LDFunctionARVGetUser:
    Type: AWS::Serverless::Function
    DependsOn: LDLayerARVEnvs
    Properties:
      FunctionName: arv-get-user
      CodeUri: lambda/functions/arv-get-user/
      Role: !GetAtt IARoleARVLambda.Arn
      Layers:
        - !Ref LDLayerARVEnvs
