
  ASDataSourceARVLDGetUser:
    Type: AWS::AppSync::DataSource
    Properties: 
      ApiId: !GetAtt ASGraphQLApiARV.ApiId
      LambdaConfig:
        LambdaFunctionArn: !GetAtt LDFunctionARVGetUser.Arn
      Name: LDGetUser
      ServiceRoleArn: !GetAtt IARoleARVAppSync.Arn
      Type: AWS_LAMBDA
